/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-02-27 09:50:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html1.naver;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class naver_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

request.setCharacterEncoding("UTF-8");

String cp = request.getContextPath(); //cp는 ContextPath의 약자

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".text_box {\r\n");
      out.write("\r\n");
      out.write("  width:500px;\r\n");
      out.write("  height:50px;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".birth {\r\n");
      out.write("  width:160px;\r\n");
      out.write("  height:50px;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".birth2 {\r\n");
      out.write("  width:160px;\r\n");
      out.write("  height:55px;\r\n");
      out.write("  font-size:20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".button {\r\n");
      out.write(" width: 510px;\r\n");
      out.write(" height: 50px;\r\n");
      out.write(" font-size: 15px;\r\n");
      out.write(" color:white;\r\n");
      out.write(" background-color: #01C707\r\n");
      out.write("}\r\n");
      out.write(".checkbox {\r\n");
      out.write(" width: 510px;\r\n");
      out.write(" height: 50px;\r\n");
      out.write(" font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".checkbox2 {\r\n");
      out.write(" width: 255px;\r\n");
      out.write(" height: 50px;\r\n");
      out.write(" font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write(".button2 {\r\n");
      out.write(" width: 245px;\r\n");
      out.write(" height: 55px;\r\n");
      out.write(" font-size: 15px;\r\n");
      out.write(" color:white;\r\n");
      out.write(" background-color: #01C707\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function idpwCheck() {\r\n");
      out.write("		\r\n");
      out.write("		var f = document.myForm;\r\n");
      out.write("	\r\n");
      out.write("		if(!f.id.value) {\r\n");
      out.write("\r\n");
      out.write("			alert(\"아이디입력!\");\r\n");
      out.write("			document.myForm.id.focous();\r\n");
      out.write("			return;\r\n");
      out.write("			}\r\n");
      out.write("		if(!f.pwd.value) {\r\n");
      out.write("		\r\n");
      out.write("			alert(\"비밀번호입력!\");\r\n");
      out.write("			f.pwd.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(!f.pwd2.value) {\r\n");
      out.write("		\r\n");
      out.write("			alert(\"비밀번호재확인!\");\r\n");
      out.write("			document.myForm.pwd2.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(f.pwd.value != f.pwd2.value) {\r\n");
      out.write("		\r\n");
      out.write("			alert(\"비밀번호가 다릅니다!\");\r\n");
      out.write("			document.myForm.pwd1.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(!f.name.value) {\r\n");
      out.write("		\r\n");
      out.write("			alert(\"이름을 입력!\");\r\n");
      out.write("			document.myForm.name.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		if(!f.birth1.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"년도 입력!\");\r\n");
      out.write("			document.myForm.birth1.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(f.birth2.value == \"월\") {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"월입력!\");\r\n");
      out.write("			document.myForm.birth2.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(!f.birth3.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"일 입력!\");\r\n");
      out.write("			document.myForm.birth3.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		if(f.gender.value ==\"성별\") {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"성별 선택해라!\");\r\n");
      out.write("			document.myForm.gender.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(!f.email.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"이메일 입력!\");\r\n");
      out.write("			document.myForm.email.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(!f.choice.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"국가 선택!\");\r\n");
      out.write("			document.myForm.choice.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(!f.tel.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"전화번호 입력!\");\r\n");
      out.write("			document.myForm.tel.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(!f.phone.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"인증번호 입력\");\r\n");
      out.write("			document.myForm.phone.focous();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		alert(\"회원가입 성공!!!!!\")\r\n");
      out.write("		\r\n");
      out.write("		f.action=\"");
      out.print(cp);
      out.write("/html1/naver/naver_ok.jsp\";\r\n");
      out.write("		f.submit();\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#f5f6f7\">\r\n");
      out.write("\r\n");
      out.write("<form action=\"\" method=\"post\" name=\"myForm\">\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\" >\r\n");
      out.write("<img src=\"nana.PNG\"/>\r\n");
      out.write("\r\n");
      out.write("<table style=\"font-size: 15pt; font-family: 돋움\" cellpadding=\"3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>                      \r\n");
      out.write("	<td><b>아이디</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"text\" class=\"text_box\"  name=\"id\" size=\"40\" placeholder=\"아이디입력\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><b>비밀번호</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("		<input type=\"password\" class=\"text_box\"  placeholder=\"비밀번호 입력\"\r\n");
      out.write("		style=\"background : url('잠금이미지.PNG') no-repeat;  background-position: 95%\"; name=\"pwd\" ;>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><b>비밀번호 재확인</b></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"password\" name=\"pwd2\" class=\"text_box\"  placeholder=\"비밀번호 재확인\"\r\n");
      out.write("	style=\"background : url('잠금이미지.PNG') no-repeat;  background-position: 95%\";></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><strong>이름</strong></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"text\" name=\"name\" class=\"text_box\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><strong>생년월일</strong></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"text\" name=\"birth1\"  class=\"birth\" placeholder=\"년도\"> \r\n");
      out.write("	<select name=\"birth2\" class=\"birth2\">\r\n");
      out.write("	<option>월</option>\r\n");
      out.write("	<option>1월</option>\r\n");
      out.write("	<option>2월</option>\r\n");
      out.write("	<option>3월</option>\r\n");
      out.write("	<option>4월</option>\r\n");
      out.write("	<option>5월</option>\r\n");
      out.write("	<option>6월</option>\r\n");
      out.write("	<option>7월</option>\r\n");
      out.write("	<option>8월</option>\r\n");
      out.write("	<option>9월</option>\r\n");
      out.write("	<option>10월</option>\r\n");
      out.write("	<option>11월</option>\r\n");
      out.write("	<option>12월</option>\r\n");
      out.write("	\r\n");
      out.write("	</select>\r\n");
      out.write(" <input type=\"text\" name=\"birth3\" class=\"birth  placeholder=\"이름입력\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><strong>성별</strong></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("	<select name=\"gender\" class=\"checkbox\" >\r\n");
      out.write("	<option>성별</option>\r\n");
      out.write("	<option>남성</option>\r\n");
      out.write("	<option>여성</option>\r\n");
      out.write("	</select>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><strong>이메일</strong></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><input type=\"text\" name=\"email\" class=\"text_box\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td><strong>휴대전화</strong></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("	<select name=\"choice\" class=\"checkbox\">\r\n");
      out.write("	<option>선택</option>\r\n");
      out.write("	<option>대한민국</option>\r\n");
      out.write("	<option>영국</option>\r\n");
      out.write("	<option>캐나다</option>\r\n");
      out.write("	</select>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("	<input type=\"text\" name=\"tel\" class=\"checkbox2\" placeholder=\"전화번호 입력\">\r\n");
      out.write("	<button class=\"button2\">인증번호받기</button>\r\n");
      out.write("	<!-- <input type=\"button\" style=\"width: 100px; height: 25px;\"> -->\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("	<input type=\"text\" name=\"phone\" class=\"text_box\"  placeholder=\"인증번호 입력하세요\" ></td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("	<button type=\"button\" onclick=\"idpwCheck()\" class=\"button\">가입하기</button>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
