/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-02-27 02:10:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1645169478000L));
    _jspx_dependants.put("jar:file:/C:/java/shopping/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/study/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp );
      out.write("/member/css/style.css\" >\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function login() {\r\n");
      out.write("		\r\n");
      out.write("		var f = document.myForm;\r\n");
      out.write("		\r\n");
      out.write("		if(!f.userId.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"아이디를 입력하세요.\");\r\n");
      out.write("			f.userId.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(!f.userPwd.value) {\r\n");
      out.write("			\r\n");
      out.write("			alert(\"패스워드를 입력하세요.\");\r\n");
      out.write("			f.userPwd.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		f.action = \"");
      out.print(cp);
      out.write("/join/login_ok.do\";\r\n");
      out.write("		f.submit();\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<center>\r\n");
      out.write("<form action=\"\" method=\"post\" name=\"myForm\">\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\r\n");
      out.write("<tr height=\"2\"><td colspan=\"2\" bgcolor=\"#cccccc\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"30\">\r\n");
      out.write("	<td colspan=\"2\" align=\"center\">\r\n");
      out.write("	<b>로그인</b>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"2\"><td colspan=\"2\" bgcolor=\"#cccccc\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"25\">\r\n");
      out.write("	<td width=\"80\" bgcolor=\"#e6e4e6\" align=\"center\">아이디</td>\r\n");
      out.write("	<td width=\"120\" style=\"padding-left: 5px;\">\r\n");
      out.write("	<input type=\"text\" name=\"userId\" maxlength=\"10\" size=\"15\"/>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"25\">\r\n");
      out.write("	<td width=\"80\" bgcolor=\"#e6e4e6\" align=\"center\">패스워드</td>\r\n");
      out.write("	<td width=\"120\" style=\"padding-left: 5px;\">\r\n");
      out.write("	<input type=\"password\" name=\"userPwd\" maxlength=\"10\" size=\"15\"/>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"2\"><td colspan=\"2\" bgcolor=\"#cccccc\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"30\">\r\n");
      out.write("	<td colspan=\"2\" align=\"center\">\r\n");
      out.write("	<input type=\"button\" value=\"로그인\" class=\"btn2\" onclick=\"login();\">\r\n");
      out.write("	<input type=\"button\" value=\"취소\" class=\"btm2\" \r\n");
      out.write("	onclick=\"javascript:location.href='");
      out.print(cp);
      out.write("/'\">\r\n");
      out.write("	<input type=\"button\" value=\" 회원가입 \" class=\"btm2\" \r\n");
      out.write("	onclick=\"javascript:location.href='");
      out.print(cp);
      out.write("/join/created.do';\">\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"30\">\r\n");
      out.write("	<td colspan=\"2\" align=\"center\">\r\n");
      out.write("	<font color=\"red\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></font>  <!-- el로 받았으니까 서블릿에서 받아올것이다 -->\r\n");
      out.write("	<font color=\"red\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></font>\r\n");
      out.write("	<font color=\"red\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message3 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></font>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<!-- 비밀번호 찾기 만들기 -->\r\n");
      out.write("<tr height=\"2\" ><td colspan=\"2\"  bgcolor=\"#cccccc\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"30\">\r\n");
      out.write("	<td colspan=\"2\" align=\"center\">\r\n");
      out.write("	<a href=\"javascript:location.href='");
      out.print(cp );
      out.write("/join/searchpw.do';\">비밀번호 찾기</a>\r\n");
      out.write("	</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr height=\"2\"><td colspan=\"2\" bgcolor=\"#cccccc\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
